# Copyright 2026, Virtioso
#
# SPDX-License-Identifier: Apache-2.0

inherit cargo externalsrc cargo-update-recipe-crates

EXTERNALSRC = "${TOPDIR}/../../sources/virtioso-muxd"
EXTERNALSRC_BUILD = "${EXTERNALSRC}"

CARGO_LOCK_SRC_DIR = "${EXTERNALSRC}"

LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://${TOPDIR}/../../sources/virtioso-muxd/LICENSE;md5=0215f7e684a6a05e27d4cf5e15d9cfcf"
SUMMARY = "virtioso-muxd: multiplexes named process streams over a single UART using the 0xfe frame protocol"

PACKAGE_ARCH = "${MACHINE_ARCH}"

# Crate checksums are generated by:
#   bitbake virtioso-muxd -c update_crates
# and stored in virtioso-muxd-crates.inc.
require ${PN}-crates.inc

SRC_URI += "file://virtioso-muxd.service"

do_install:append() {
    install -d ${D}${systemd_unitdir}/system
    install -m 0644 ${UNPACKDIR}/virtioso-muxd.service \
        ${D}${systemd_unitdir}/system/
}

SYSTEMD_SERVICE:${PN} = "virtioso-muxd.service"
SYSTEMD_AUTO_ENABLE:${PN} = "disable"
inherit systemd
